site_name: User's API
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: deep orange
plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

extra_css:
  - css/mkdocsoad.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

