site_name: User's API
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: deep orange
  logo: assets/images/ourlogo.png
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

repo_url: https://github.com/lananovikova10/api-docs-course
repo_name: api-docs-course
extra_css:
  - css/mkdocsoad.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true

